services:
  strava-puns-webhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strava-puns-webhook
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/puns.db
    volumes:
      - ./data:/app/data
      - ./puns.json:/app/puns.json:ro
    restart: unless-stopped
    networks:
      - cf-tunnel

networks:
  cf-tunnel:
    external: true
